In [2]:
# The FunctionTransformer is a tool in scikit-learn, a popular Python library for machine learning,
# that allows you to apply a specified function to the input data.

# The FunctionTransformer can be useful for performing custom transformations of input data in a machine learning pipeline.

In [1]:
# The FunctionTransformer takes as input a single function that will be applied to each sample in the data. 
# This function can be any Python function that takes a single argument, such as a lambda function or a user-defined function. 
# The function should return the transformed sample.
# The FunctionTransformer takes as input a single function that will be applied to each sample in the data.
# This function can be any Python function that takes a single argument, such as a lambda function or a user-defined function.
# The function should return the transformed sample.

In [3]:
from sklearn.preprocessing  import FunctionTransformer
import numpy as np 

#  create data set  
x = np.array([[1,2],[3,4]])

#define  the  transformation  function  
log_transform  =  FunctionTransformer(np.log1p)

# apply  the transformation  to  the  data set  
x_transformed   =  log_transform.transform(x)

# view the  transformed  data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]

In [5]:
# second  example  
#create data set 
z = np.array([[1,2],[3,4]])
# create a custom feature engineering function 
def squ(x):
    return np.hstack((x,x**2))
# create FunctionTransformer to  apply  the  custom  function
custom_transformer  = FunctionTransformer(squ) 
# apply  the  transformer to  the  input data  
x_transformed  =  custom_transformer.transform(x)
# view the  transform  data  
print(x_transformed)  #   show  normal  array  and  its  squared  array

[[ 1  2  1  4]
 [ 3  4  9 16]]

In [7]:
# thrid example  

# craete  data  set 
s = np.array([[1,2],[3,4]])

# define a  custome  scaling  function
def  my_scaling(s):
    return s / np.max(s)
    
#create  a function  transformer  to  apply  the  custom  function  
customtransformer =  FunctionTransformer(my_scaling)

# apply the  transformer  to  the  input  data  
transformed_tf = customtransformer.transform(x)

# VIEW THE  TRANSFORMED  DATA  
print(transformed_tf)

[[0.25 0.5 ]
 [0.75 1.  ]]

In [13]:
# Q.4  
# create data set  with  missing  value  
r = np.array([[1,2],[3,np.nan]])

# define  custom  cleaning  function  
def  my_cleaning(r):
    r[np.isnan(r)] = 0 
    return r
# create a function  TransFormer to  apply  the  custom function  
custom1 = FunctionTransformer(my_cleaning) 

# apply the  transformer  to the  inpute data 
x_transformed_2 = custom1.transform(r)
# view the  transformed  data 
print(x_transformed_2)

[[1. 2.]
 [3. 0.]]

In [17]:
import  numpy as  np 
import  pandas  as  pd  
df  =  pd.read_csv('newplacementdata - newplacementdata.csv')
df.head()

   cgpa  placement_exam_marks  placed
0  7.19                    26       1
1  7.46                    38       1
2  7.54                    40       1
3  6.42                     8       1
4  7.23                    17       0

In [18]:
x=df.drop(columns=['placed'])
y=df['placed']

In [19]:
from  sklearn.preprocessing  import FunctionTransformer

In [20]:
log_transform =  FunctionTransformer(np.log1p)

In [22]:
#apply the  transformation on  data set
transformed_3 = log_transform.transform(x)
transformed_3

         cgpa  placement_exam_marks
0    2.102914              3.295837
1    2.135349              3.663562
2    2.144761              3.713572
3    2.004179              2.197225
4    2.107786              2.890372
..        ...                   ...
995  2.289500              3.806662
996  2.314514              4.189655
997  1.773256              3.555348
998  2.263844              3.850148
999  1.774952              2.397895

[1000 rows x 2 columns]